### PR TITLE
Fix #17, Fix Doxygen Warnings

### LINKED ISSUE #17: Fix doxygen warnings
**Describe the bug**
Warnings are generated when building the documentation.

**To Reproduce**
1. Do `make doc` from the cFS directory
2. Observe the warnings in `cFS/build/doc/warnings.log`

**Expected behavior**
No warnings should be generated

**Reporter Info**
Leor Bleier GSFC\582

### PR DESCRIPTION
**Pull request by lbleier-GSFC**
**Describe the contribution**
Fixes #17 to resolve doxygen warnings

**Testing performed**
Steps taken to test the contribution:

1. Corrected lines that generated warnings
2. Rebuilt documentation with `make doc`
3. Observed no warnings generated
4. Viewed relevant page(s) to verify correctness

**Expected behavior changes**
Changes to documentation only; no code impact

**Contributor Info - All information REQUIRED for consideration of pull request**
Leor Bleier, NASA\GSFC

### CODE REVIEW

File: fsw/public_inc/sample_lib.h [hunk 1]
```diff
@@ -52,9 +52,8 @@
 **  \par Assumptions, External Events, and Notes:
 **        None
 **
-**  \returns
-**  \retstmt Returns #CFE_SUCCESS if successful \endcode
-**  \endreturns
+**  \returns Returns #CFE_SUCCESS
```
Comment (skliper) [inline fsw/public_inc/sample_lib.h:55]: Suggest - ` \return Execution status, see \ref CFEReturnCodes`

**Comment by skliper** [comment]
20200422 CCB - APPROVED
